// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/renderer.proto

package renderer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid           int32                  `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	HeapAddr      uint64                 `protobuf:"varint,3,opt,name=heap_addr,json=heapAddr,proto3" json:"heap_addr,omitempty"`
	HeapSize      uint64                 `protobuf:"varint,4,opt,name=heap_size,json=heapSize,proto3" json:"heap_size,omitempty"`
	Fd            int32                  `protobuf:"varint,5,opt,name=fd,proto3" json:"fd,omitempty"`
	NrOpenat      int32                  `protobuf:"varint,6,opt,name=nr_openat,json=nrOpenat,proto3" json:"nr_openat,omitempty"`
	NrMmap        int32                  `protobuf:"varint,7,opt,name=nr_mmap,json=nrMmap,proto3" json:"nr_mmap,omitempty"`
	NrWrite       int32                  `protobuf:"varint,8,opt,name=nr_write,json=nrWrite,proto3" json:"nr_write,omitempty"`
	NrFsync       int32                  `protobuf:"varint,9,opt,name=nr_fsync,json=nrFsync,proto3" json:"nr_fsync,omitempty"`
	Checksum      uint32                 `protobuf:"varint,10,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Palette       string                 `protobuf:"bytes,11,opt,name=palette,proto3" json:"palette,omitempty"`
	Wave          int32                  `protobuf:"varint,12,opt,name=wave,proto3" json:"wave,omitempty"`
	Distortion    int32                  `protobuf:"varint,13,opt,name=distortion,proto3" json:"distortion,omitempty"`
	Grain         int32                  `protobuf:"varint,14,opt,name=grain,proto3" json:"grain,omitempty"`
	Border        int32                  `protobuf:"varint,15,opt,name=border,proto3" json:"border,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_proto_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_proto_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RenderRequest) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *RenderRequest) GetHeapAddr() uint64 {
	if x != nil {
		return x.HeapAddr
	}
	return 0
}

func (x *RenderRequest) GetHeapSize() uint64 {
	if x != nil {
		return x.HeapSize
	}
	return 0
}

func (x *RenderRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *RenderRequest) GetNrOpenat() int32 {
	if x != nil {
		return x.NrOpenat
	}
	return 0
}

func (x *RenderRequest) GetNrMmap() int32 {
	if x != nil {
		return x.NrMmap
	}
	return 0
}

func (x *RenderRequest) GetNrWrite() int32 {
	if x != nil {
		return x.NrWrite
	}
	return 0
}

func (x *RenderRequest) GetNrFsync() int32 {
	if x != nil {
		return x.NrFsync
	}
	return 0
}

func (x *RenderRequest) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *RenderRequest) GetPalette() string {
	if x != nil {
		return x.Palette
	}
	return ""
}

func (x *RenderRequest) GetWave() int32 {
	if x != nil {
		return x.Wave
	}
	return 0
}

func (x *RenderRequest) GetDistortion() int32 {
	if x != nil {
		return x.Distortion
	}
	return 0
}

func (x *RenderRequest) GetGrain() int32 {
	if x != nil {
		return x.Grain
	}
	return 0
}

func (x *RenderRequest) GetBorder() int32 {
	if x != nil {
		return x.Border
	}
	return 0
}

type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PngData       []byte                 `protobuf:"bytes,1,opt,name=png_data,json=pngData,proto3" json:"png_data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_proto_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_proto_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderResponse) GetPngData() []byte {
	if x != nil {
		return x.PngData
	}
	return nil
}

func (x *RenderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_renderer_proto protoreflect.FileDescriptor

const file_proto_renderer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/renderer.proto\x12\brenderer\"\x81\x03\n" +
	"\rRenderRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\x05R\x03tid\x12\x1b\n" +
	"\theap_addr\x18\x03 \x01(\x04R\bheapAddr\x12\x1b\n" +
	"\theap_size\x18\x04 \x01(\x04R\bheapSize\x12\x0e\n" +
	"\x02fd\x18\x05 \x01(\x05R\x02fd\x12\x1b\n" +
	"\tnr_openat\x18\x06 \x01(\x05R\bnrOpenat\x12\x17\n" +
	"\anr_mmap\x18\a \x01(\x05R\x06nrMmap\x12\x19\n" +
	"\bnr_write\x18\b \x01(\x05R\anrWrite\x12\x19\n" +
	"\bnr_fsync\x18\t \x01(\x05R\anrFsync\x12\x1a\n" +
	"\bchecksum\x18\n" +
	" \x01(\rR\bchecksum\x12\x18\n" +
	"\apalette\x18\v \x01(\tR\apalette\x12\x12\n" +
	"\x04wave\x18\f \x01(\x05R\x04wave\x12\x1e\n" +
	"\n" +
	"distortion\x18\r \x01(\x05R\n" +
	"distortion\x12\x14\n" +
	"\x05grain\x18\x0e \x01(\x05R\x05grain\x12\x16\n" +
	"\x06border\x18\x0f \x01(\x05R\x06border\"A\n" +
	"\x0eRenderResponse\x12\x19\n" +
	"\bpng_data\x18\x01 \x01(\fR\apngData\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2T\n" +
	"\x0fRendererService\x12A\n" +
	"\fRenderPoster\x12\x17.renderer.RenderRequest\x1a\x18.renderer.RenderResponseB3Z1github.com/dennisdijkstra/memprint/proto/rendererb\x06proto3"

var (
	file_proto_renderer_proto_rawDescOnce sync.Once
	file_proto_renderer_proto_rawDescData []byte
)

func file_proto_renderer_proto_rawDescGZIP() []byte {
	file_proto_renderer_proto_rawDescOnce.Do(func() {
		file_proto_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_renderer_proto_rawDesc), len(file_proto_renderer_proto_rawDesc)))
	})
	return file_proto_renderer_proto_rawDescData
}

var file_proto_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_renderer_proto_goTypes = []any{
	(*RenderRequest)(nil),  // 0: renderer.RenderRequest
	(*RenderResponse)(nil), // 1: renderer.RenderResponse
}
var file_proto_renderer_proto_depIdxs = []int32{
	0, // 0: renderer.RendererService.RenderPoster:input_type -> renderer.RenderRequest
	1, // 1: renderer.RendererService.RenderPoster:output_type -> renderer.RenderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_renderer_proto_init() }
func file_proto_renderer_proto_init() {
	if File_proto_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_renderer_proto_rawDesc), len(file_proto_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_renderer_proto_goTypes,
		DependencyIndexes: file_proto_renderer_proto_depIdxs,
		MessageInfos:      file_proto_renderer_proto_msgTypes,
	}.Build()
	File_proto_renderer_proto = out.File
	file_proto_renderer_proto_goTypes = nil
	file_proto_renderer_proto_depIdxs = nil
}
