package main

import (
	"fmt"
	"math"

	"github.com/fogleman/gg"
)

const posterWidth = 400
const posterHeight = 600

func renderPoster(layout Layout) (*gg.Context, error) {
	dc := gg.NewContext(posterWidth, posterHeight)

	// dark background
	dc.SetHexColor("#080808")
	dc.Clear()

	for _, el := range layout.Elements {
		if err := drawElement(dc, el); err != nil {
			return nil, fmt.Errorf("draw element %q: %w", el.Content, err)
		}
	}

	drawFooter(dc)

	return dc, nil
}

func drawElement(dc *gg.Context, el LayoutElement) error {
	if err := loadFont(dc, el.Size); err != nil {
		return err
	}

	dc.Push()
	defer dc.Pop()

	dc.Translate(el.X+float64(posterWidth/2), el.Y)
	dc.Rotate(el.Rotation * math.Pi / 180)

	if el.SkewX != 0 {
		dc.Shear(math.Tan(el.SkewX*math.Pi/180), 0)
	}

	switch el.Effect {
	case "aberration":
		drawAberration(dc, el)
	default:
		drawPlain(dc, el)
	}

	return nil
}

func drawAberration(dc *gg.Context, el LayoutElement) {
	// red layer offset left
	dc.SetRGBA(1, 0, 0.24, el.Opacity*0.75)
	dc.DrawStringAnchored(el.Content, -8, 0, 0.5, 0.5)
	dc.Fill()

	// blue layer offset right
	dc.SetRGBA(0, 0.81, 1, el.Opacity*0.75)
	dc.DrawStringAnchored(el.Content, 8, 6, 0.5, 0.5)
	dc.Fill()

	// white master on top
	dc.SetRGBA(0.94, 0.94, 0.94, el.Opacity)
	dc.DrawStringAnchored(el.Content, 0, 0, 0.5, 0.5)
	dc.Fill()

}

func drawPlain(dc *gg.Context, el LayoutElement) {
	r, g, b := effectColour(el.Effect)
	dc.SetRGBA(r, g, b, el.Opacity)
	dc.DrawStringAnchored(el.Content, 0, 0, 0.5, 0.5)
}

func effectColour(effect string) (float64, float64, float64) {
	switch effect {
	case "pool":
		return 1, 1, 1
	case "drag":
		return 0.90, 0.90, 0.90
	case "melt":
		return 0.85, 0.85, 0.85
	case "ghost":
		return 0.80, 0.80, 0.80
	case "warp":
		return 0.94, 0.94, 0.94
	default:
		return 1, 1, 1
	}
}

func loadFont(dc *gg.Context, size float64) error {
	fonts := []string{
		"/System/Library/Fonts/SFNSMono.ttf",
		"/System/Library/Fonts/SFNSMonoItalic.ttf",
		"/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf", // Linux fallback for Docker
	}

	for _, path := range fonts {
		if err := dc.LoadFontFace(path, size); err == nil {
			return nil
		}
	}

	return fmt.Errorf("no usable font found")
}

func drawFooter(dc *gg.Context) {
	dc.SetRGBA(1, 1, 1, 0.08)
	dc.SetLineWidth(0.4)
	dc.DrawLine(10, float64(posterHeight)-22, float64(posterWidth)-10, float64(posterHeight)-22)
	dc.Stroke()

	if err := loadFont(dc, 6); err != nil {
		return
	}
	dc.SetRGBA(1, 1, 1, 0.2)
	dc.DrawStringAnchored("MEMPRINT · generated by your process",
		float64(posterWidth)/2, float64(posterHeight)-10, 0.5, 0.5)
	dc.Fill()
}
