package main

import (
	"fmt"
	"math"

	"github.com/dennisdijkstra/memprint/shared/events"
	"github.com/fogleman/gg"
)

const posterWidth = 400
const posterHeight = 600

func renderPoster(layout Layout, meta events.MemMetadata) (*gg.Context, error) {
	dc := gg.NewContext(posterWidth, posterHeight)

	// paper background
	dc.SetHexColor("#EDEAE2")
	dc.Clear()

	// layer 1 — journey diagram
	drawJourneyDiagram(dc, meta)

	// layer 2 — linocut typography on top
	for _, el := range layout.Elements {
		if err := drawElement(dc, el); err != nil {
			return nil, fmt.Errorf("draw element %q: %w", el.Content, err)
		}
	}

	return dc, nil
}

func drawElement(dc *gg.Context, el LayoutElement) error {
	if err := loadFont(dc, el.Size); err != nil {
		return err
	}

	dc.Push()
	defer dc.Pop()

	dc.Translate(el.X+float64(posterWidth/2), el.Y)
	dc.Rotate(el.Rotation * math.Pi / 180)

	if el.SkewX != 0 {
		dc.Shear(math.Tan(el.SkewX*math.Pi/180), 0)
	}

	switch el.Effect {
	case "aberration":
		drawAberration(dc, el)
	default:
		drawPlain(dc, el)
	}

	return nil
}

func drawAberration(dc *gg.Context, el LayoutElement) {
	// red layer
	dc.SetRGBA(0.8, 0, 0.15, el.Opacity*0.75)
	dc.DrawStringAnchored(el.Content, -8, 0, 0.5, 0.5)
	dc.Fill()

	// blue layer
	dc.SetRGBA(0, 0, 0.8, el.Opacity*0.75)
	dc.DrawStringAnchored(el.Content, 8, 6, 0.5, 0.5)
	dc.Fill()

	// black master on top
	dc.SetRGBA(0.07, 0.07, 0.07, el.Opacity)
	dc.DrawStringAnchored(el.Content, 0, 0, 0.5, 0.5)
	dc.Fill()
}

func drawPlain(dc *gg.Context, el LayoutElement) {
	r, g, b := effectColour(el.Effect)
	dc.SetRGBA(r, g, b, el.Opacity)
	dc.DrawStringAnchored(el.Content, 0, 0, 0.5, 0.5)
}

func effectColour(effect string) (float64, float64, float64) {
	switch effect {
	case "pool":
		return 0.07, 0.07, 0.07 // near black
	case "drag":
		return 0.1, 0.1, 0.1
	case "melt":
		return 0.08, 0.08, 0.08
	case "ghost":
		return 0.15, 0.15, 0.15
	case "warp":
		return 0.07, 0.07, 0.07
	default:
		return 0.07, 0.07, 0.07
	}
}

func loadFont(dc *gg.Context, size float64) error {
	fonts := []string{
		"./fonts/SpecialElite-Regular.ttf", // Docker + local
		"services/render/fonts/SpecialElite-Regular.ttf",
		"/System/Library/Fonts/SFNSMono.ttf", // fallback
	}

	for _, path := range fonts {
		if err := dc.LoadFontFace(path, size); err == nil {
			return nil
		}
	}
	return fmt.Errorf("no usable font found")
}

func drawFooter(dc *gg.Context) {
	dc.SetRGBA(1, 1, 1, 0.08)
	dc.SetLineWidth(0.4)
	dc.DrawLine(10, float64(posterHeight)-22, float64(posterWidth)-10, float64(posterHeight)-22)
	dc.Stroke()

	if err := loadFont(dc, 6); err != nil {
		return
	}
	dc.SetRGBA(1, 1, 1, 0.2)
	dc.DrawStringAnchored("MEMPRINT · generated by your process",
		float64(posterWidth)/2, float64(posterHeight)-10, 0.5, 0.5)
	dc.Fill()
}
